### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by originlan** [wp529/Exposure#1]
朋友，有遮盖的时候，例如tablayout或者自定义的固定head有方案么

**Comment by wp529** [comment]
> 朋友，有遮盖的时候，例如tablayout或者自定义的固定head有方案么

不知道你的具体曝光场景是什么，可以详细描述下么？

**Comment by wp529** [comment]
> 朋友，有遮盖的时候，例如tablayout或者自定义的固定head有方案么

你是指RV在ViewGroup中有与RV平级的View把RV遮挡了一部分的情况吗？

**Comment by originlan** [comment]
> > 朋友，有遮盖的时候，例如tablayout或者自定义的固定head有方案么
> 
> 你是指RV在ViewGroup中有与RV平级的View把RV遮挡了一部分的情况吗？

大致是这个意思，是有一个动态tabbar和rv平级，上滑一定高度，tabbar会盖在rv之上，所以一个item移动到可视区域之外（tabbar之下）时，并没有结束曝光，而是要继续移动到屏幕之外，才能结束曝光，需要一个cover方法来检查可见性Rect的属性。

**Comment by wp529** [comment]
> > > 朋友，有遮盖的时候，例如tablayout或者自定义的固定head有方案么
> > 
> > 
> > 你是指RV在ViewGroup中有与RV平级的View把RV遮挡了一部分的情况吗？
> 
> 大致是这个意思，是有一个动态tabbar和rv平级，上滑一定高度，tabbar会盖在rv之上，所以一个item移动到可视区域之外（tabbar之下）时，并没有结束曝光，而是要继续移动到屏幕之外，才能结束曝光，需要一个cover方法来检查可见性Rect的属性。

朋友，处理了遮挡的情况，你试试1.1.6版本呢
