### ISSUE TITLE
感谢大兄弟，rl嵌套rl的时候各自还有曝光，这种情况怎么处理

### ISSUE THREAD

**Issue by originlan** [wp529/Exposure#2]
如题，感谢大兄弟，rl嵌套rl的时候各自还有曝光，这种情况怎么处理

**Comment by wp529** [comment]
> 如题，感谢大兄弟，rl嵌套rl的时候各自还有曝光，这种情况怎么处理

出于性能考虑，如果父布局设置了曝光，那么就不会再往下传递了。如果又要父布局支持曝光，又要子布局支持曝光，那么父布局不使用曝光RL，在布局中添加一个与父布局相同大小的空白View设置曝光。
