### ISSUE TITLE
在ViewPager嵌套Fragment的情况会出现统计可见区域不准的情况

### ISSUE THREAD

**Issue by hy20160705** [wp529/Exposure#3]
感谢提供思路
如题 在ViewPager嵌套Fragment的情况会出现统计可见区域不准的情况
当TabLayout+ViewPager+Fragment的结构时 特别是存在3个及以上的fragment实例 由第0->n(n>=3) 跨度较大的时候 由于ViewPager中内置了专场动画 将会导致fragment的resume的生命周期调用早于ViewPager动画结束，也就是内部的recyclerView.post { }提前调用 在去计算可见区域的时候`getGlobalVisibleRect(currentViewRect)`得到的currentViewRect不准确，导致埋点不准确
目前我这边的解决方案有一下3种
* 根据观察ViewPager源码 转场动画最多600ms 可以使用recyclerView.postDelay的方案去解决
   更改代码
   ```kotlin
    fun onVisible() {
        //....
        recyclerView.postDelayed({ firstRecordExposureData() }, 610)
    }
   ```
   ViewPager代码之smoothScrollTo(int x, int y, int velocity)
   ```java
       //.....
       int duration;
        velocity = Math.abs(velocity);
        if (velocity > 0) {
            duration = 4 * Math.round(1000 * Math.abs(distance / velocity));
        } else {
            final float pageWidth = width * mAdapter.getPageWidth(mCurItem);
            final float pageDelta = (float) Math.abs(dx) / (pageWidth + mPageMargin);
            duration = (int) ((pageDelta + 1) * 100);
        }
        duration = Math.min(duration, MAX_SETTLE_DURATION);

        // Reset the "scroll started" flag. It will be flipped to true in all places
        // where we call computeScrollOffset().
        mIsScrollStarted = false;
        mScroller.startScroll(sx, sy, dx, dy, duration);
        ViewCompat.postInvalidateOnAnimation(this);
   ```
* 关闭ViewPager的转场动画
* 监听ViewPage的滑动状态 `ViewPager.addOnPageChangeListener` 结合onPageScrollStateChanged(int state) 主动通知fragment的onVisible()和onInvisible()
这是我提供的一些思路供参考 老哥若是有其他比较好的解决方案 请艾特我
感谢

**Comment by wp529** [comment]
感谢老哥反馈。如你所说，由于我使用Lifecycle对生命周期监听来自动处理开始/结束曝光，它可以在简单的场景下正确处理，但在此场景下并不能按我们所想的那样对生命周期进行回调，更复杂的场景下，比如我公司项目中MainActivity中使用ViewPager，ViewPager里有个首页Fragment，首页Fragment中又有TabLayout+ViewPager+Fragment，对这个子子fragment里的RecyclerView进行曝光处理想通过Lifecycle实现自动处理开始/结束曝光完全做不到。所以此库里提供的onVisible和onInvisible方法就是用于此类场景下：当Lifecycle没按预期回调时可以由我们自行告知类库处理开始/结束曝光。所以我建议你采用第三种解决方案。再次感谢你的反馈。
