### ISSUE TITLE
请问Recyclerview中的Adapter有子Recyclerview，子RecyclerView有合适的上报方式吗

### ISSUE THREAD

**Issue by hysea** [wp529/Exposure#4]

**Comment by wp529** [comment]
你是什么场景呢？我们项目中也有此类场景，是竖直滑动的RV里有水平滑动的RV，需要对水平滑动RV的item做曝光埋点吗？

**Comment by hysea** [comment]
> RV

嗯嗯，就是类似的场景

**Comment by hysea** [comment]
嗯嗯，就是这类场景曝光

**Comment by wp529** [comment]
可以给子RV的item使用实现了IProvideExposureData的布局，然后和之前一样绑定好曝光数据，再给子RV设置一个滚动监听，在此滚动监听中调用父RV的RecyclerViewExposureHelper.onScroll即可。

**Comment by wp529** [comment]
由于此库的实现逻辑，所以前提是子RV的父布局和父父布局等上层布局都没有使用实现了IProvideExposureData的布局，不然会被上层布局拦截掉。

**Comment by hysea** [comment]
> 可以给子RV的item使用实现了IProvideExposureData的布局，然后和之前一样绑定好曝光数据，再给子RV设置一个滚动监听，在此滚动监听中调用父RV的RecyclerViewExposureHelper.onScroll即可。

理论上这样应该会重复提交父RV的曝光数据吧；

**Comment by hysea** [comment]
请问可以提供一份demo示例吗

**Comment by wp529** [comment]
> > 可以给子RV的item使用实现了IProvideExposureData的布局，然后和之前一样绑定好曝光数据，再给子RV设置一个滚动监听，在此滚动监听中调用父RV的RecyclerViewExposureHelper.onScroll即可。
> 
> 理论上这样应该会重复提交父RV的曝光数据吧；

不会重复提交，因为光是子RV滑动的时候，父RV中所有的item曝光状态都没有发生改变，我呆会儿提交一份RV嵌套RV的曝光示例，稍等

**Comment by hysea** [comment]
非常谢谢🙏

**Comment by wp529** [comment]
demo提交了,RvInRvActivity你看看有帮助没呢

**Comment by wp529** [comment]
我demo里是把曝光拆成了两部分，如果你想父容器整体算做一个曝光单位的话，那父容器你不能使用实现了IProvideExposureData的布局，而是在父容器下写一个透明的View，使得此透明View与父容器相同大小，即可实现。
![1C77FAD7-FA83-41FC-946E-4B0074C6F5B0](https://user-images.githubusercontent.com/18145495/198186304-5c897037-2d3f-4f9d-8dea-a6568655fb3d.png)

**Comment by wp529** [comment]
总之原则是，一个可采集曝光的View不能嵌套在另一个可采集曝光的View中，否则只会采集顶层可采集曝光View的曝光状态。

**Comment by hysea** [comment]
问题解决了，感谢！！
