### ISSUE TITLE
删除屏幕中的某个item，可能会有屏幕外的item进入屏幕，但没有被感知

### ISSUE THREAD

**Issue by wiatt-code** [wp529/Exposure#5]
这是一个很好用的库，但在使用过程中发现一个比较严重的问题。如下：
        当删除屏幕中的某个item，可能会出现屏幕外的item进入屏幕内的情况，此item应该是需要被感知的，但是目前来看并没有。
    经研究，是由于recyclerView的item默认动画未执行完，就已经开始检测item暴露情况了，此时的item还处于屏幕外，当item进入屏幕后，暴露检测工作已经结束并认为item暴露面积不足。
    在注释中发现作者已经发现该问题，并有解决策略，但并没有加以解决。个人的具体解决方案：在 ViewTreeObserver.OnGlobalLayoutListener 类的 onGlobalLayout 方法中加入以下代码：

`RecyclerView.ItemAnimator itemAnimator = recyclerView.getItemAnimator();
                        if (itemAnimator == null) {
                            Log.i("TAG", "onGlobalLayout: 没有 item 动画");
                        } else {
                            itemAnimator.isRunning(new RecyclerView.ItemAnimator.ItemAnimatorFinishedListener() {
                                @Override
                                public void onAnimationsFinished() {
                                    // 原来的代码迁移到这
                                    recyclerView.post(new Runnable() {
                                        @Override
                                        public void run() {
                                            recordExposureData();
                                        }
                                    });
                                }
                            });
                        }`

望作者修复改问题

**Comment by wp529** [comment]
感谢你的反馈，已修复改问题，请使用v1.2.3版本
