### ISSUE TITLE
如果 RecyclerView 中只剩下一个 item，删除该 item 后，得不到移除暴露反馈

### ISSUE THREAD

**Issue by wiatt-code** [wp529/Exposure#6]
经研究，该问题是由于 getVisibleItemPositionRange 函数中的 如下代码导致的：
`return if (visibleItemPositionRange == null
            || visibleItemPositionRange.firstVisibleItemPosition < 0
            || visibleItemPositionRange.lastVisibleItemPosition < 0
        ) {
            null
        } else {
            visibleItemPositionRange
        }`
当 recyclerView 中没有 item 后，firstVisibleItemPosition 和 lastVisibleItemPosition  都变成 -1。之后的流程就走不下去了。
我的解决策略是：将判断中的 0 改为 -1。
但是值得注意的是，我并不确定这里的判断是否是作者为了应对其他场景下的问题而有意为之。

望回复

**Comment by wp529** [comment]
感谢反馈，当时想的是可见条目的起始和末尾position必定是大于0的，如果出现小于0的情况则代表某些地方出了异常，阻止后续逻辑执行，未考虑到删除为空的情况。改此问题打算在RecyclerView.AdapterDataObserver的数据更新回调中判断如果RV数据更新为空，则将所有处于曝光中的item都置为结束曝光。

**Comment by wiatt-code** [comment]
> 感谢反馈，当时想的是可见条目的起始和末尾position必定是大于0的，如果出现小于0的情况则代表某些地方出了异常，阻止后续逻辑执行，未考虑到删除为空的情况。改此问题打算在RecyclerView.AdapterDataObserver的数据更新回调中判断如果RV数据更新为空，则将所有处于曝光中的item都置为结束曝光。

针对这个问题有修改并更新版本吗？如果改了，我就直接依赖你的，目前没有发现其他问题。

**Comment by wp529** [comment]
稍等，我打个新版本

**Comment by wp529** [comment]
版本已打好，可以依赖
 `implementation 'com.github.wp529:Exposure:1.2.4'`
同时再次感谢你的反馈，也期待你提供PR帮助完善此库。
